config/routes.rb
Rails.application.routes.draw do
  get 'contacts/new'
  get 'contacts/confirm'
  get 'contacts/done'
  devise_for :users


  root to: "homes#top"
  get "home/about" => "homes#about"
  get "search" => "searches#search"
  delete 'book/:id' => 'books#destroy', as: 'destroy_book'

  resources :books
  resources :users

  resources :books, only: [:new, :create, :index, :show, :destroy] do
    resource :favorite, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
end

  resources :contacts, only: [:new, :create] do
  collection do
      post 'confirm'
      post 'back'
      get 'done'
  end
end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :books, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_one_attached :profile_image

  validates :name, presence: true, length: { in: 2..20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }


   #validates :title, presence: true
  #validates :body, presence: true
 def get_profile_image(width, height)
  unless profile_image.attached?
    file_path = Rails.root.join('app/assets/images/no_image.jpg')
    profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  end
  profile_image.variant(resize_to_limit: [width, height]).processed
end

  # 検索方法分岐
  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end

  GUEST_USER_EMAIL = "guest@example.com"

  def self.guest
    find_or_create_by!(email: GUEST_USER_EMAIL) do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
  end
  end


  def guest_user?
    email == GUEST_USER_EMAIL
  end

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to user_path(user), notice: "guestuserでログインしました。"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]
  before_action :ensure_guest_user, only: [:edit]

  def show
  @user = User.find(params[:id])
  @books = @user.books
  end


  def edit
  @user = User.find(params[:id])
  end


  def index
  @user = User.find(current_user.id)
  @book = Book.new
  @users = User.all
  end

  def update
  @user = User.find(params[:id])
  if @user.update(user_params)

    # 4. フラッシュメッセージを定義
      flash[:notice] = "Book was successfully created."
      redirect_to user_path(@user.id)
  else
      render :edit#この記述を追加
  end

  def create
  @user = User.new(user_params)
  @user.user_id = current_user.id
  if @user.save
      redirect_to user_path
  else
      render :new
  end
  end


  end




  private
  def user_params
      params.require(:user).permit(:name, :introduction, :profile_image)
  end


  # ここから追加
  def is_matching_login_user
    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to user_path(current_user.id)
    end
  end
  # ここまで追加

  # ユーザーの編集画面へのURLを直接入力された場合にはメッセージを表示してユーザー詳細画面へリダイレクト
   def ensure_guest_user
    @user = User.find(params[:id])
    if @user.guest_user?
      redirect_to user_path(current_user) , notice: "ゲストユーザーはプロフィール編集画面へ遷移できません。"
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_list.html.erb
<h2>User info</h2>

<p>画像</p>
  <%= image_tag 'no_image',  size: "100x100" %>
  
<table>
  <tr></tr>
  <tr>
    <th>name</th><th><%= @user.name %></th>
  </tr>
  <tr>
    <th>introduction</th><th><%= @user.introduction %></th>
  </tr>
</table>

<li>
  <a class = "btn btn-outline-secondary btn-block edit_user_163274", <%= link_to  edit_user_path(current_user.id), class: "nav-link text-light" do  %><i class="fa-solid fa-wrench"></i></a>
  <% end %>
</li>

app/views/users/edit.html.erb
<div class = "container">
<div class ="row">

<div class = "col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">

<h2>User info</h2>
<% if @user.errors.any? %>
  <%= @user.errors.count %>件のエラーが発生しました
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @user do |f| %>
  <label for="inputName">Name</label>
   <br>
  <%= f.text_field :name, autofocus: true, id:"name", placeholder:""%>
  <br>
  <label for="inputImage">Image</label>
   <br>
  <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %>  
  <br>
  <label for="inputName">Introduction</label>
   <br>
   <%= f.text_field :introduction, autofocus: true, id:"introduction", placeholder:""%>
  <br> 
  <%= f.submit "Update User" %>
<% end %>

</div>
</div>
</div>

app/views/users/index.html.erb
 <div class ="container">
  <div class = "row">
  <div class ="col-md-3">
 <%= render 'books/list', books: @book %>
  </div>
   <div class ="col-md-8 offset-md-1">
     <h2>Users</h2>
    <table class = "table table-hover table-inverse">
 <thead>
 <tr>

  <th>image</th>
  <th>name</th>
  <th colspan="1"></th>
  </tr>
  </thead>

  <tbody>
   <% @users.each do |user| %>
   <tr>
     <td><%=image_tag user.get_profile_image(100,100) %></td>
     <td><%=user.name %></td>

   <td><%= link_to "Show", user_path(user.id)  %></td>

   </tr>


   <% end %>


  </tbody>
  </table>

app/views/users/show.html.erb
<div class ="container">
  <div class = "row">
  <div class ="col-md-3">
 <%= render 'books/list', books: @book %>

  </div>
   <div class ="col-md-8 offset-md-1">
     <h2>Books</h2>


 <table class = "table table-hover table-inverse">
 <thead>
 <tr>
 <th></th>
  <th>Title</th>
  <th>Opinion</th>
  </tr>
  </thead>

  <tbody>
   <% @books.each do |book| %>
   <tr>
     <td><%= link_to user_path(book.user.id) do %>
     <%=image_tag book.user.get_profile_image(100,100) %>
    <% end %></td>
     <td><%= link_to book.title, book_path(book.id) %></td>
     <td><%=book.body %></td>

   </tr>
   <% end %>


  </tbody>
  </table>