config/routes.rb
Rails.application.routes.draw do
  get 'contacts/new'
  get 'contacts/confirm'
  get 'contacts/done'
  devise_for :users


  root to: "homes#top"
  get "home/about" => "homes#about"
  get "search" => "searches#search"
  delete 'book/:id' => 'books#destroy', as: 'destroy_book'

  resources :books
  resources :users

  resources :books, only: [:new, :create, :index, :show, :destroy] do
    resource :favorite, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
end

  resources :contacts, only: [:new, :create] do
  collection do
      post 'confirm'
      post 'back'
      get 'done'
  end
end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end
end

app/models/contact.rb
class Contact < ApplicationRecord
  
  validates :name, presence: true
  validates :email, presence: true
  validates :subject, presence: true
  validates :message, presence: true
  
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def new
    @contact = Contact.new
  end

  def confirm
    @contact = Contact.new(contact_params)
    if @contact.invalid?
      flash[:alert] = @contact.errors.full_messages.join(", ")
      @contact = Contact.new
      render :new
    end
  end

  def back
    @contact = Contact.new(contact_params)
    render :new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      ContactMailer.send_mail(@contact).deliver_now
      redirect_to done_contacts_path
    else
      flash[:alert] = @contact.errors.full_messages.join(", ")
      @contact = Contact.new
      render :new
    end
  end

  def done
  end

    private

    def contact_params
      params.require(:contact).permit(:name, :email, :subject, :message)
    end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/confirm.html.erb
<div class="container p-5">
  <div class="row">
    <div class="col-md-10 offset-md-1">

      <table class="table">
        <tbody>
          <tr>
            <td class="text-right" style="width: 30%;">お名前</td>
            <td><%= @contact.name %></td>
          </tr>
          <tr>
            <td class="text-right mt-3" style="width: 30%;">メールアドレス</td>
            <td><%= @contact.email %></td>
          </tr>
          <tr>
            <td class="text-right mt-3" style="width: 30%;">件名</td>
            <td><%= @contact.subject %></td>
          </tr>
          <tr>
            <td class="text-right mt-3">メッセージ</td>
            <td style="white-space: pre-wrap;"><%= @contact.message %></td>
          </tr>
        </tbody>
      </table>

      <div class="d-flex">
        <div class="mr-3">
        <%= form_with model: @contact do |f| %>
          <%= f.hidden_field :name %>
          <%= f.hidden_field :email %>
          <%= f.hidden_field :subject %>
          <%= f.hidden_field :message %>
          <div><%= f.submit '送信', class: "btn btn-success" %></div>
        <% end %>
        </div>

        <div>
        <%= form_with model: @contact, url: back_contacts_path do |f| %>
          <%= f.hidden_field :name %>
          <%= f.hidden_field :email %>
          <%= f.hidden_field :subject %>
          <%= f.hidden_field :message %>
          <div><%= f.submit '入力画面に戻る', class: "btn btn-info" %></div>
        <% end %>
        </div>
      </div>


    </div>
  </div>
</div>

app/views/contacts/done.html.erb
<div class="container p-5">
  <h5 class="text-center">お問い合わせありがとうございました。</h5>
</div>

app/views/contacts/new.html.erb
<div class="container-fluid light-blue-container p-5">
  <div class="row">
    <div class="col-md-8 offset-md-2">

    <div class="mb-2">
      <%= flash[:alert] %>
    </div>
    <h2>お問い合わせ</h2>

      <%= form_with model: @contact, url: confirm_contacts_path, local: true do |f| %>
        <div class="form-group">
          <%= f.label :name, 'お名前' %><span class="text-danger">*</span>
          <%= f.text_field :name, autofocus: true, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :email, 'メールアドレス' %><span class="text-danger">*</span>
          <%= f.email_field :email, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :subject, '件名' %><span class="text-danger">*</span>
          <%= f.text_area :subject, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :message, 'メッセージ' %><span class="text-danger">*</span>
          <%= f.text_area :message, size: '10x10', class: 'form-control' %>
        </div>

        <div>
          <%= f.submit '入力内容確認', class: "btn btn-outline-info bg-white" %>
        </div>
      <% end %>

    </div>
  </div>
</div>