config/routes.rb
Rails.application.routes.draw do
  get 'contacts/new'
  get 'contacts/confirm'
  get 'contacts/done'
  devise_for :users


  root to: "homes#top"
  get "home/about" => "homes#about"
  get "search" => "searches#search"
  delete 'book/:id' => 'books#destroy', as: 'destroy_book'

  resources :books
  resources :users

  resources :books, only: [:new, :create, :index, :show, :destroy] do
    resource :favorite, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
end

  resources :contacts, only: [:new, :create] do
  collection do
      post 'confirm'
      post 'back'
      get 'done'
  end
end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end
end

app/models/book.rb
class Book < ApplicationRecord
  # attr_accessor クラス内で簡単にインスタンス変数の値を読み書きすることができる
  attr_accessor :tag_list
  after_save :tag_update
  after_find :to_tag_list
  has_many :book_tags
  has_many :tags, through: :book_tags

  belongs_to :user
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

  #ソート機能
  scope :latest, -> {order(created_at: :desc)}
  scope :old, -> {order(created_at: :asc)}
  scope :star_count, -> {order(star: :desc)}


  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  # 検索方法分岐
  def self.looks(search, word)
    if search == "perfect_match"
      @book = Book.where("title LIKE?", "#{word}")
    elsif search == "forward_match"
      @book = Book.where("title LIKE?","#{word}%")
    elsif search == "backward_match"
      @book = Book.where("title LIKE?","%#{word}")
    elsif search == "partial_match"
      @book = Book.where("title LIKE?","%#{word}%")
    else
      @book = Book.all
    end
  end

  private

  def tag_update
    # 削除した際に古いタグを取り出す記述
    old_tags = self.tags.pluck(:name)
    # /[[:space:]]/が全角の際にはじいてくれて、split(",")カンマ区切りでuniqで重複しない記述(新しいタグの記述)
    tags = self.tag_list.gsub(/[[:space:]]/, "").split(",").uniq
    
    # タグをレコードする(レコードに含まれているものを探す)
    tags.each do |tag_name|
      #タグ１つずつに対してあったら見つけてきてなかったら作ってね記述
      tag = Tag.find_or_create_by(name: tag_name)
      self.book_tags.find_or_create_by(tag_id: tag.id)
    end
    
    # 古いタグについての記述方法
    delete_tags = old_tags - tags
    delete_tags.each do |tag_name|
      tag = Tag.find_by(name: tag_name)
      book_tag = self.book_tags.find_by(tag_id: tag.id)
      # 他にtagを誰か使っていないかの記述
      if tag.book_tags.size <= 1
        tag.destroy
      else
        book_tag.destroy
      end
    end
  end

  def to_tag_list
    self.tag_list = self.tags.pluck(:name).join(", ")
    self
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :ensure_correct_user, only: [:edit, :update, :destroy]

  def index
    @books = Book.all
    @book = Book.new
    @user = current_user
    
    if params[:latest]
     @books = Book.latest
    elsif params[:old]
     @books = Book.old
    elsif params[:star_count]
     @books = Book.star_count
    else
     @books = Book.all
  end
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
    flash[:notice] = "You have created book successfully."
    redirect_to book_path(@book.id)
    else
      @user = current_user
      @books = Book.all
      render :index
    end

  end

  def show
    @book = Book.find(params[:id])
    @book_new = Book.new
    @user = @book.user
    @post_comment = PostComment.new
  end

  def edit
    @book = Book.find(params[:id])
  end

  def destroy
    book = Book.find(params[:id])  # データ（レコード）を1件取得
    book.destroy  # データ（レコード）を削除
    redirect_to '/books'  # 投稿一覧画面へリダイレクト
  end

  def update
    @book = Book.find(params[:id])

  if @book.update(book_params)

    # 4. フラッシュメッセージを定義
      flash[:notice] = "Book was successfully created."
      redirect_to book_path(@book.id)
  else
      render :edit#この記述を追加
  end
  end

  def ensure_correct_user
    @book = Book.find(params[:id])
    unless @book.user.id == current_user.id
      redirect_to books_path
    end
  end

  private
  def book_params
      params.require(:book).permit(:title, :body, :star, :tag_list)
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_list.html.erb
<h2>User info</h2>
<p>画像</p>
  <%= image_tag 'no_image',  size: "100x100" %>
<table>
  <tr></tr>
  <tr>
    <th>name</th><th><%= @user.name %></th>
  </tr>
  <tr>
    <th>introduction</th><th><%= @user.introduction %></th>
  </tr>
</table>

<!--ゲストユーザーがプロフィール編集画面を行えないようにする-->
<% unless @user.guest_user? %>
  <li>
    <%= link_to edit_user_path(@user.id),class: "nav-link text-light" do  %>
    <i class="fa-solid fa-user-gear"></i>
    <% end %>
  </li>
<% end %>

<h2>New book</h2>

  <%= form_with model: Book.new do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>
  <h4>Opinion</h4>
  <%= f.text_area :body %>
  <h4>Tag</h4>
  <%= f.text_field :tag_list %>
  <%= f.submit 'Create Book' %>

  <!--評価表示部位-->
<div id="stars">
<label>Rate</label>
</div>

<script>
  let elem = document.querySelector('#stars');
  let opt = {
    starOn: "<%= asset_path('star-on.png') %>",
    starOff: "<%= asset_path('star-off.png') %>",
    scoreName: 'book[star]'
  };
  window.raty(elem, opt);
</script>




<!--% books.each do |book| %>
<!-- @books → books -->

<% end %>

app/views/books/edit.html.erb
<h2>Editing Book</h2>
<% if @book.errors.any? %>
  <%= @book.errors.count %>
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<br>
<%= form_with model: @book do |f| %>
  <label for="inputName">Title</label>
  <br>
  <%= f.text_field :title %>
  <br>
  <label for="inputName">Opinion</label>
  <br>
   <%= f.text_field :body %>
   <br>
   <%= f.text_field :tag_list %>
  <%= f.submit "Update Book" %>
  <br>
  <td>
  <% if @book.user == current_user %>
  <%= link_to "Show", book_path(@book.id) %>
  <%end%>
  </td
  <td>
  <% if @book.user == current_user %>
  <%= link_to "Back", books_path %>
  <%end%>
  </td
<% end %>

app/views/books/index.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this obj from being saved:

  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>


<div class ="container">
  <div class = "row">
  <div class ="col-md-3">
 <%= render 'list', books: @book %>
  </div>
   <div class ="col-md-8 offset-md-1">
     <%= render 'searches/search' %>
     <h2>Books</h2>
     <%= link_to '新しい順', books_path(latest: "true") %>
     <%= link_to '古い順', books_path(old: "true") %>
     <%= link_to '評価の高い順', books_path(star_count: "true") %>

 <table class = "table table-hover table-inverse">
  <thead>
   <tr>
    <th>Title</th>
    <th>Opinion</th>
    <th colspan="3"></th>
   </tr>
  </thead>

  <tbody>
   <% @books.each do |book| %>
  <tr>
  <td>
   <%= link_to user_path(book.user_id)  do  %>
   <%= image_tag book.user.get_profile_image(100,100)%>
   <% end %>
 </td>

<td>
  <%= link_to book.title, book_path(book.id)  %>
</td>

<td>
  <p><%= link_to "#{book.post_comments.count} コメント", book_path(book.id) %></p>
</td>
 <td>
  <%= book.body %>
 </td>
 </tr>

 <% end %>
 </tbody>
 </table>
  </div>
</div>
</div>

app/views/books/show.html.erb
<div class ="container">
  <div class = "row">
  <div class ="col-md-3">
<%= render 'list', books: @book_new %>
</div>


<div class ="col-md-8 offset-md-1">

  <h2>Book detail</h2>
  <table class = "table" >
    <tbody>
    <tr>
     <td>
       <%= image_tag @book.user.get_profile_image(100,100) %><br><%= link_to @book.user.name,user_path(@book.user_id) %>
     </td>
     <td>
       <%= @book.title %>
     </td>
     <td>
        <%= @book.body %>
     </td>

     <td id="favorite_buttons_<%= @book.id %>" >
            <%= render "favorites/favorite", book: @book %>
            
    <!--レビュー機能追加      -->
     <div id="show-stars"></div>
      <script>
        let showRateElement = document.querySelector('#show-stars');
        let showOpt = {
          starOn: "<%= asset_path('star-on.png') %>",
          starOff: "<%= asset_path('star-off.png') %>",
          scoreName: 'book[star]',
          score: "<%= @book.star %>",
          readOnly: true
        };
        window.raty(showRateElement, showOpt);
      </script>	      
            

     <td>
       <% if @book.user == current_user %>
       <%= link_to "Edit", edit_book_path(@book.id) %>
       <%end%>
     </td>
     <td>
        <% if @book.user == current_user %>
       <%= link_to "Destroy", book_path(@book.id),method: :delete,"data-confirm" => "本当に削除しますか？" %>
       <%end%>
     </td>
    </tr>
    </tbody>
     </table>

<div id="post-comments">
  <%= render "post_comments/comments" , { book: @book , post_comment: @post_comment } %><br>
</div>
<div id="comment-form">
  <%= render "post_comments/form" , { book: @book , post_comment: @post_comment } %>
</div>
</div>
  </div>
</div>
</div>