config/routes.rb
Rails.application.routes.draw do
  get 'contacts/new'
  get 'contacts/confirm'
  get 'contacts/done'
  devise_for :users


  root to: "homes#top"
  get "home/about" => "homes#about"
  get "search" => "searches#search"
  delete 'book/:id' => 'books#destroy', as: 'destroy_book'

  resources :books
  resources :users

  resources :books, only: [:new, :create, :index, :show, :destroy] do
    resource :favorite, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
end

  resources :contacts, only: [:new, :create] do
  collection do
      post 'confirm'
      post 'back'
      get 'done'
  end
end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers3</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/c3fd8eb30a.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>


  <header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
        <a class="navbar-brand" href="/">
          <span>Bookers</span>
        </a>
        <div class ="collapse navbar-collapse">
          <ul class = "navbar-nav ml-auto">
    <% if user_signed_in? %>

      <li>

        <%= link_to  user_path(current_user), class: "nav-link text-light" do  %>
         <i class="fa-solid fa-house"></i>Home
         <%end%>
      </li>
      <li>
         <%= link_to  users_path, class: "nav-link text-light" do  %>
         <i class="fa-solid fa-users"></i>Users
          <%end%>

      </li>
      <li>
        <%= link_to  books_path, class: "nav-link text-light" do  %>
        <i class="fa-solid fa-book-open"></i>Books

          <%end%>
      </li>
       <li>
          <%= link_to  destroy_user_session_path, method: :delete, class: "nav-link text-light" do  %>
         <i class="fa-solid fa-right-from-bracket"></i>Log out
        　<%end%>
      </li>
      <li>
        <%= link_to   new_contact_path, class: "nav-link text-light" do  %>
         <i class="fa-solid fa-right-to-bracket"></i></i>Contact
         <%end%>
      </li>

    <% else %>

      <li>
      　 <%= link_to  root_path, class: "nav-link text-light" do  %>
         <i class="fa-solid fa-house"></i>Home
         <%end%>
      </li>
      <li>
         <%= link_to  home_about_path, class: "nav-link text-light" do  %>
          <i class="fa-solid fa-link"></i></i>About
          <%end%>
      </li>
      <li>
         <%= link_to  new_user_registration_path, class: "nav-link text-light" do  %>
         <i class="fa-solid fa-user-plus"></i></i>Sign up
         <%end%>
      </li>
      <li>
        <%= link_to   new_user_session_path, class: "nav-link text-light" do  %>
         <i class="fa-solid fa-right-to-bracket"></i></i>Log in
         <%end%>
      </li>
      <li>
        <%= link_to   new_contact_path, class: "nav-link text-light" do  %>
         <i class="fa-solid fa-right-to-bracket"></i></i>Contact
         <%end%>
      </li>

    <% end %>
    </ul>
    </div>
  </div>
  </nav>
  </header>




  <main>
    <div>
    <%= flash[:notice] %>
    </div>
    <%= yield %>
  </main>

  <footer>
  <p>CopyRight Infratop.inc</p>
  </footer>
  </body>
</html>